/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package egkerpen_wegfinder;

import db.DBController;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import listenklassen.List_extended;

/**
 *
 * @author User
 */
public class DBAktualisiere extends javax.swing.JFrame {
    File f;
    Writer fw;
    DBController r;
    List_extended<List_extended<String>> l;
    String[][] s;
    int i;

    /**
     * Creates new form DBAktualisiere
     */
    public DBAktualisiere() {
        initComponents();
        
        try {
            f = new File("dbContent.txt");
            fw = new FileWriter(f);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        r = DBController.getInstance();
        l = new List_extended<>();
        
        getAllTeachers();
        
        i = 0;
        try {
            lehrer.setText(s[i][1] + " " + s[i][0]);
        }
        catch(ArrayIndexOutOfBoundsException e) {
            DBInitialise.main(null);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bWeiter = new javax.swing.JButton();
        raum = new javax.swing.JComboBox();
        lehrer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Lehrer:");

        jLabel2.setText("Raum:");

        bWeiter.setText("Weiter >>");
        bWeiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWeiter(evt);
            }
        });

        raum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- (Verhindert)", "Raum 38", "Raum 39", "Raum 42", "Raum 63", "Raum 64", "Raum 65", "Raum 66", "Raum 67", "Raum 70", "Raum 71", "Raum 72", "Raum 73", "Raum 87", "Raum 88", "Raum 89", "Raum 90", "Raum 92", "Raum 93", "Raum 94", "Raum 95", "Raum 96", "Raum 97", "Raum 104", "Raum 106", "Raum 107", "Raum 108", "Raum 109", "Raum 110", "Raum 132", "Raum 134", "Raum 135", "Raum 136", "Raum 137", "Raum 141", "Raum 142", "Raum 144", "Raum 145", "Raum 150", "Raum 151", "Raum 154", "Raum 155", "Raum 156", "Raum 166", "Raum 167", "Raum 168", "Raum 169", "Raum 170", "Raum 171", "Raum 174", "Raum 175", "Raum 184", "Raum 185", "Raum 188", "Raum 189", "Raum 190", "Raum 191", "Raum 192/193", "Raum 200", "Raum 203/204", "Raum 205", "Raum 206", "Raum 208", "Raum 209", "Raum 210", "Raum 212", "Raum 213", "Raum 215", "Raum 216", "Raum 217", "Raum 218", "Raum 219", "Raum 220", "Raum 222", "Raum 223", "Raum 227", "Raum 228", "Raum 229", "Raum 230", "Raum 231", "Raum 235", "Raum 236", "Raum 237", "Raum 238", "Raum 240", "Raum 241", "Raum 242", "Raum 250", "Raum 251", "Raum 253", "Raum 254", "Raum 255", "Raum 262", "Raum 263", "Raum 264", "Raum 266", "Raum 267", "Raum 269", "Raum 270", "Raum 283", "Raum 284", "Raum 286", "Raum 288", "Raum 289", "Raum 290", "Raum 293", "Raum 302", "Raum 303", "Raum 304", "Raum 305", "Raum 306", "Raum 307", "Raum 308", "Raum 309", "Raum 310", "Raum 311", "Raum 312", "Raum 313", "Raum 314", "Werkraum 8", "Werkraum 14", "Werkraum 15", "Werkraum 17", "Werkraum 20", "Werkraum 21", "Werkraum 24", "Werkraum 27", "Werkraum 32", "Kunstraum 53", "Kunstraum 59", "Technikraum 62", "Mensa", "Büro der Schulleitung/Sekretariat", "Büro der stellv. Schulleitung", "Saftladen", "Spielekeller", "Bibliothek" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lehrer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bWeiter, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(22, 22, 22)
                            .addComponent(raum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lehrer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bWeiter)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bWeiter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWeiter
        try {
            String verhindert = "0";

            if(String.valueOf(raum.getSelectedItem()).startsWith("-"))
            verhindert = "1";

            fw.write(String.valueOf(raum.getSelectedItem()) + ";" + s[i][0] + ";" + s[i][1] + ";" + verhindert);
            fw.append(System.getProperty("line.separator"));
            fw.flush();

            i++;
        } catch (IOException e) {
            e.printStackTrace();
        }

        if(i == s.length){
            DBController r = DBController.getInstance();

            if(r.dbInitialise(f)){

                try {
                    fw.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }

                EGKerpen_Wegfinder.main(null);
                this.dispose();
            }
        } else {
            lehrer.setText(s[i][1] + " " + s[i][0]);
        }
    }//GEN-LAST:event_bWeiter

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBAktualisiere().setVisible(true);
            }
        });
    }
    
    /**
     * This method gets all teachers saved in the database.
     */
    private void getAllTeachers() {
        r.executeQuery("SELECT DISTINCT * FROM lehrer ORDER BY nachname");
        
        l = r.getResults();
        
        s = new String[r.getResultsAmount()][2];
            
            l.toFirst();
            
            for(int i = 0; i < s.length; i++){
                List_extended<String> l2 = l.getObject();
                l2.toFirst();
                
                for(int j = 0; j < s[i].length; j++){
                    s[i][j] = l2.getObject();
                    l2.next();
                }
                
                l.next();
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bWeiter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lehrer;
    private javax.swing.JComboBox raum;
    // End of variables declaration//GEN-END:variables
}
