/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package egkerpen_wegfinder;

import graphklassen.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JLabel;
import listenklassen.*;

/**
 *
 * @author User
 */
public class GroundPlanPanel extends javax.swing.JPanel {

    private Graph schoolGraph;
    private Dijkstra d;
    private List<GraphNode> path;
    private final Image gpImage;
    private int bgSideLength, standardSideLength;
    private double diff;
    private int xOffset, yOffset;
    private Content content;
    private boolean drawAll;
    JLabel[] nodeNames;
    
    /**
     * Creates new form GroundPlanPanel
     * @param content Parent 'Content' Object
     */
    public GroundPlanPanel(Content content) {
        initComponents();
        buildGraph();
        d = new Dijkstra(schoolGraph);
        gpImage = new ImageIcon(getClass().getResource("EGKerpen_Grundriss.png")).getImage();
        standardSideLength = gpImage.getWidth(this);
        path = new List<>();
        this.content = content;
        drawAll = true;
        nodeNames = new JLabel[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Draws the path from 'start' to 'dest' on the background image.
     * @param start
     * @param dest 
     */
    public void drawPath(String start, String dest){
        /**
        * Exclude this line to check every path of the graph.
        */
        path = d.getPath(schoolGraph.getNode(start),schoolGraph.getNode(dest));
        
        
        // For debugging use only
        path.toFirst();
        while(path.hasAccess()){
            System.out.println(path.getObject().getName());
            path.next();
        }
        path.toFirst();
        /**
        * Include these lines to check every path of the graph.
        */
        /* path = d.getPath(schoolGraph.getNode(s1[i]), schoolGraph.getNode(s2[j]));
        
        if(j == s2.length - 1){
            j = 0;
            i++;
        } else j++;
        */
        
        repaint();
    } 
    
    /**
     * Paints the Panel with the background and the path 
     * and considers the scaling of the window.
     * @param g 
     */
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        updateOffsets();
        this.setBounds(xOffset, yOffset, bgSideLength, bgSideLength);
        g.drawImage(gpImage, 0, 0, bgSideLength, bgSideLength,this);
        
        NumberFormat n = NumberFormat.getInstance();
        n.setMaximumFractionDigits(2);
        
        if(!path.isEmpty()){
            g.setColor(Color.red);
            GraphNode n1, n2;
            
            if(!drawAll) {
                path.toFirst();

                n1 = path.getObject();

                path.next();

                while(path.hasAccess()){
                    n2 = path.getObject();

                    if(!(n1.getName().charAt(0) == 'T' && n2.getName().charAt(0) == 'T')){
                        g.fillRect(n1.getX() - 1, n1.getY() - 1, 3, 3);
                        g.drawLine(n1.getX(), n1.getY(), n2.getX(), n2.getY());
                        g.fillRect(n2.getX() - 1, n2.getY() - 1, 3, 3);
                    }

                    n1 = n2;
                    path.next();
                }

                g.setColor(Color.green);

                path.toFirst();
                g.fillRect(path.getObject().getX() - 2, path.getObject().getY() - 2, 5, 5);

                path.toLast();
                g.fillRect(path.getObject().getX() - 2, path.getObject().getY() - 2, 5, 5);
            }
            else {
                List<GraphNode> nodes = schoolGraph.getNodes();
                nodes.toFirst();
                int nodesCount = 0;
                while(nodes.hasAccess()) {
                    nodesCount++;
                    nodes.next();
                }
                if(nodeNames.length == 0) {
                    nodeNames = new JLabel[nodesCount];
                }
                else {
                    
                }
                nodes.toFirst();
                int counter = 0;
                GraphNode node;
                System.out.println(diff);
                while(nodes.hasAccess()) {
                    node = nodes.getObject();
                    g.fillRect((int) (diff * node.getX())-1, (int) (diff * node.getY())-1, 3, 3);
                    if(nodeNames[counter] == null) {
                        nodeNames[counter] = new JLabel(node.getName());
                        nodeNames[counter].setFont(new Font(nodeNames[counter].getFont().getName(), Font.PLAIN, 8));
                        nodeNames[counter].setBounds((int) (diff * node.getX()),(int) (diff *  node.getY()), 100, 8);
                        this.add(nodeNames[counter]);
                    }
                    else {
                        nodeNames[counter].setLocation((int) (diff * node.getX()),(int) (diff *  node.getY()));
                    }
                    counter++;
                    nodes.next();
                }
            }
        }
    }
    
    /**
     * Updates the side length of the panel/background and sets the offsets
     * depending on the window scale.
     */
    private void updateOffsets() {
        bgSideLength = Math.min(this.getHeight(), this.getWidth());
        xOffset = (content.getWidth() - bgSideLength) / 2;
        yOffset = 51;
        diff = (double) bgSideLength / standardSideLength;
    }
    
    public void drawAllPoints(boolean state) {
        drawAll = state;
    }
    
    /**
     * This method builds the graph containing rooms, waypoints and stairs.
     */
    private void buildGraph(){
        schoolGraph = new Graph();
                // Nodes:
        
            // Ground floor:
        
        // Stairs:
        
        schoolGraph.addNode(new GraphNode("T1_0", 520, 656));
        schoolGraph.addNode(new GraphNode("T2_0", 640, 670));
        schoolGraph.addNode(new GraphNode("T3_0", 632, 608));
        schoolGraph.addNode(new GraphNode("T4_0", 551, 519));
        schoolGraph.addNode(new GraphNode("T5_0", 608, 520));
        schoolGraph.addNode(new GraphNode("T6_0", 536, 805)); // Finished
        
        // Waypoints:
        
        schoolGraph.addNode(new GraphNode("P000", 539, 684));
        schoolGraph.addNode(new GraphNode("P001", 530, 684));
        schoolGraph.addNode(new GraphNode("P002", 483, 684));
        schoolGraph.addNode(new GraphNode("P003", 466, 684));
        schoolGraph.addNode(new GraphNode("P004", 540, 656));
        schoolGraph.addNode(new GraphNode("P005", 550, 656));
        schoolGraph.addNode(new GraphNode("P007", 589, 683));
        schoolGraph.addNode(new GraphNode("P008", 538, 632));
        schoolGraph.addNode(new GraphNode("P010", 506, 584));
        schoolGraph.addNode(new GraphNode("P011", 506, 574));
        schoolGraph.addNode(new GraphNode("P012", 506, 534));
        schoolGraph.addNode(new GraphNode("P013", 543, 548));
        schoolGraph.addNode(new GraphNode("P014", 543, 504));
        schoolGraph.addNode(new GraphNode("P016", 543, 472));
        schoolGraph.addNode(new GraphNode("P017", 543, 457));
        schoolGraph.addNode(new GraphNode("P018", 558, 448));
        schoolGraph.addNode(new GraphNode("P019", 608, 448));
        schoolGraph.addNode(new GraphNode("P020", 632, 448));
        schoolGraph.addNode(new GraphNode("P021", 649, 448));
        schoolGraph.addNode(new GraphNode("P022", 645, 467));
        schoolGraph.addNode(new GraphNode("P023", 645, 472));
        schoolGraph.addNode(new GraphNode("P024", 642, 535));
        schoolGraph.addNode(new GraphNode("P025", 607, 535));
        schoolGraph.addNode(new GraphNode("P026", 632, 625));
        schoolGraph.addNode(new GraphNode("P027", 654, 625));
        schoolGraph.addNode(new GraphNode("P028", 700, 625));
        schoolGraph.addNode(new GraphNode("P029", 720, 625));
        schoolGraph.addNode(new GraphNode("P030", 754, 625));
        schoolGraph.addNode(new GraphNode("P032", 787, 625));
        schoolGraph.addNode(new GraphNode("P033", 810, 625));
        schoolGraph.addNode(new GraphNode("P034", 647, 659));
        schoolGraph.addNode(new GraphNode("P035", 670, 659));
        schoolGraph.addNode(new GraphNode("P036", 670, 686));
        schoolGraph.addNode(new GraphNode("P037", 703, 686));
        schoolGraph.addNode(new GraphNode("P039", 736, 686));
        schoolGraph.addNode(new GraphNode("P040", 742, 686));
        schoolGraph.addNode(new GraphNode("P041", 742, 711));
        schoolGraph.addNode(new GraphNode("P042", 766, 686));
        schoolGraph.addNode(new GraphNode("P043", 797, 686));
        schoolGraph.addNode(new GraphNode("P044", 797, 718)); // Finished
        
        // Rooms:
        
        schoolGraph.addNode(new GraphNode("Bibliothek", 573, 683));
        schoolGraph.addNode(new GraphNode("Foyer", 589, 648));
        schoolGraph.addNode(new GraphNode("WC Herren", 482, 672));
        schoolGraph.addNode(new GraphNode("WC Damen", 466, 672));
        schoolGraph.addNode(new GraphNode("Mensa", 433, 684));
        schoolGraph.addNode(new GraphNode("Saftladen", 528, 526));
        schoolGraph.addNode(new GraphNode("Raum 38", 493, 586));
        schoolGraph.addNode(new GraphNode("Raum 39", 493, 562));
        schoolGraph.addNode(new GraphNode("Raum 42", 493, 522));
        schoolGraph.addNode(new GraphNode("Werkraum 8", 542, 440));
        schoolGraph.addNode(new GraphNode("Werkraum 14", 559, 440));
        schoolGraph.addNode(new GraphNode("Werkraum 15", 608, 440));
        schoolGraph.addNode(new GraphNode("Werkraum 17", 632, 440));
        schoolGraph.addNode(new GraphNode("Werkraum 20", 649, 440));
        schoolGraph.addNode(new GraphNode("Werkraum 21", 652, 467));
        schoolGraph.addNode(new GraphNode("Werkraum 24", 658, 486));
        schoolGraph.addNode(new GraphNode("Werkraum 27", 633, 472));
        schoolGraph.addNode(new GraphNode("Werkraum 32", 551, 472));
        //schoolGraph.addNode(new GraphNode("Kunstraum 53", 596, 586));  needs to be moved to the basement
        schoolGraph.addNode(new GraphNode("Raum 63", 700, 617));
        schoolGraph.addNode(new GraphNode("Raum 64", 719, 617));
        schoolGraph.addNode(new GraphNode("Raum 65", 754, 617));
        schoolGraph.addNode(new GraphNode("Raum 66", 784, 617));
        schoolGraph.addNode(new GraphNode("Raum 67", 812, 617));
        schoolGraph.addNode(new GraphNode("Raum 70", 812, 636));
        schoolGraph.addNode(new GraphNode("Raum 71", 794, 636));
        schoolGraph.addNode(new GraphNode("Raum 72", 756, 636));
        schoolGraph.addNode(new GraphNode("Raum 73", 735, 636));
        schoolGraph.addNode(new GraphNode("Raum 87", 738, 676));
        schoolGraph.addNode(new GraphNode("Raum 88", 766, 676));
        schoolGraph.addNode(new GraphNode("Raum 89", 799, 676));
        schoolGraph.addNode(new GraphNode("Raum 90", 809, 687));
        schoolGraph.addNode(new GraphNode("Raum 92", 809, 718));
        schoolGraph.addNode(new GraphNode("Raum 93", 798, 729));
        schoolGraph.addNode(new GraphNode("Raum 94", 788, 713));
        schoolGraph.addNode(new GraphNode("Raum 95", 751, 718));
        schoolGraph.addNode(new GraphNode("Raum 96", 734, 718));
        schoolGraph.addNode(new GraphNode("Raum 97", 703, 720)); // Finished
        
            // First floor:
        
        // Stairs:
        
        schoolGraph.addNode(new GraphNode("T1_1", 135, 469));
        schoolGraph.addNode(new GraphNode("T2_1", 285, 478));
        schoolGraph.addNode(new GraphNode("T3_1", 261, 400));
        schoolGraph.addNode(new GraphNode("T4_1", 156, 286));
        schoolGraph.addNode(new GraphNode("T5_1", 233, 289));
        schoolGraph.addNode(new GraphNode("T6_1", 156, 625));
        schoolGraph.addNode(new GraphNode("T7_1", 16, 574));
        schoolGraph.addNode(new GraphNode("T8_1", 441, 495));
        schoolGraph.addNode(new GraphNode("T9_1", 441, 427)); // Finished
        
        // Waypoints:
        
        schoolGraph.addNode(new GraphNode("P100", 39, 574));
        schoolGraph.addNode(new GraphNode("P101", 52, 574));
        schoolGraph.addNode(new GraphNode("P102", 90, 574));
        schoolGraph.addNode(new GraphNode("P103", 113, 574));
        schoolGraph.addNode(new GraphNode("P104", 128, 574));
        schoolGraph.addNode(new GraphNode("P105", 155, 574));
        schoolGraph.addNode(new GraphNode("P106", 155, 595));
        schoolGraph.addNode(new GraphNode("P107", 155, 500));
        schoolGraph.addNode(new GraphNode("P108", 143, 500));
        schoolGraph.addNode(new GraphNode("P109", 83, 500));
        schoolGraph.addNode(new GraphNode("P110", 54, 500));
        schoolGraph.addNode(new GraphNode("P111", 143, 469));
        schoolGraph.addNode(new GraphNode("P112", 155, 469));
        schoolGraph.addNode(new GraphNode("P113", 155, 451));
        schoolGraph.addNode(new GraphNode("P114", 155, 418));
        schoolGraph.addNode(new GraphNode("P115", 155, 388));
        schoolGraph.addNode(new GraphNode("P116", 155, 357));
        schoolGraph.addNode(new GraphNode("P117", 155, 339));
        schoolGraph.addNode(new GraphNode("P118", 155, 319));
        schoolGraph.addNode(new GraphNode("P119", 155, 302));
        schoolGraph.addNode(new GraphNode("P120", 185, 451));
        schoolGraph.addNode(new GraphNode("P121", 207, 451));
        schoolGraph.addNode(new GraphNode("P122", 232, 451));
        schoolGraph.addNode(new GraphNode("P123", 232, 426));
        schoolGraph.addNode(new GraphNode("P124", 232, 370));
        schoolGraph.addNode(new GraphNode("P125", 232, 332));
        schoolGraph.addNode(new GraphNode("P126", 232, 304));
        schoolGraph.addNode(new GraphNode("P127", 262, 426));
        schoolGraph.addNode(new GraphNode("P128", 316, 426));
        schoolGraph.addNode(new GraphNode("P130", 321, 426));
        schoolGraph.addNode(new GraphNode("P131", 348, 426));
        schoolGraph.addNode(new GraphNode("P132", 366, 426));
        schoolGraph.addNode(new GraphNode("P133", 387, 426));
        schoolGraph.addNode(new GraphNode("P134", 408, 426));
        schoolGraph.addNode(new GraphNode("P135", 422, 427));
        schoolGraph.addNode(new GraphNode("P136", 285, 464));
        schoolGraph.addNode(new GraphNode("P137", 316, 464));
        schoolGraph.addNode(new GraphNode("P138", 316, 498));
        schoolGraph.addNode(new GraphNode("P139", 346, 498));
        schoolGraph.addNode(new GraphNode("P140", 346, 509));
        schoolGraph.addNode(new GraphNode("P141", 389, 498));
        schoolGraph.addNode(new GraphNode("P142", 423, 498)); // Finished
        
        // Rooms:
        
        schoolGraph.addNode(new GraphNode("Lehrerzimmer", 66, 751));
        schoolGraph.addNode(new GraphNode("Büro der Schulleitung/Sekretariat", 66, 716));
        schoolGraph.addNode(new GraphNode("Büro der stellv. Schulleitung", 89, 710));
        schoolGraph.addNode(new GraphNode("Raum 104", 176, 835));
        schoolGraph.addNode(new GraphNode("Raum 106", 146, 841));
        schoolGraph.addNode(new GraphNode("Raum 107", 115, 841));
        schoolGraph.addNode(new GraphNode("Raum 108", 93, 841));
        schoolGraph.addNode(new GraphNode("Raum 109", 65, 841));
        schoolGraph.addNode(new GraphNode("Raum 110", 53, 841));
        schoolGraph.addNode(new GraphNode("Raum 132", 144, 649));
        schoolGraph.addNode(new GraphNode("Raum 134", 144, 628));
        schoolGraph.addNode(new GraphNode("Raum 135", 144, 592));
        schoolGraph.addNode(new GraphNode("Raum 136", 144, 579));
        schoolGraph.addNode(new GraphNode("Raum 137", 144, 549));
        schoolGraph.addNode(new GraphNode("Raum 141", 180, 549));
        schoolGraph.addNode(new GraphNode("Raum 142", 180, 561));
        schoolGraph.addNode(new GraphNode("Raum 144", 196, 668));
        schoolGraph.addNode(new GraphNode("Raum 145", 226, 668));
        schoolGraph.addNode(new GraphNode("Raum 150", 225, 561));
        schoolGraph.addNode(new GraphNode("Raum 151", 225, 549));
        schoolGraph.addNode(new GraphNode("Raum 154", 259, 549));
        schoolGraph.addNode(new GraphNode("Raum 155", 259, 561));
        schoolGraph.addNode(new GraphNode("Raum 156", 259, 606));
        schoolGraph.addNode(new GraphNode("Raum 166", 315, 638));
        schoolGraph.addNode(new GraphNode("Raum 167", 334, 638));
        schoolGraph.addNode(new GraphNode("Raum 168", 346, 638));
        schoolGraph.addNode(new GraphNode("Raum 169", 367, 638));
        schoolGraph.addNode(new GraphNode("Raum 170", 379, 638));
        schoolGraph.addNode(new GraphNode("Raum 171", 399, 638));
        schoolGraph.addNode(new GraphNode("Raum 174", 396, 682));
        schoolGraph.addNode(new GraphNode("Raum 175", 365, 682));
        schoolGraph.addNode(new GraphNode("Raum 184", 364, 715));
        schoolGraph.addNode(new GraphNode("Raum 185", 395, 715));
        schoolGraph.addNode(new GraphNode("Raum 188", 395, 760));
        schoolGraph.addNode(new GraphNode("Raum 189", 364, 760));
        schoolGraph.addNode(new GraphNode("Raum 190", 342, 745));
        schoolGraph.addNode(new GraphNode("Raum 191", 298, 765));
        schoolGraph.addNode(new GraphNode("Raum 192/193", 279, 734));
        
            // Second floor:
        
        // Stairs:
        
        schoolGraph.addNode(new GraphNode("T1_2", 557, 280));
        schoolGraph.addNode(new GraphNode("T2_2", 697, 290));
        schoolGraph.addNode(new GraphNode("T3_2", 694, 201));
        schoolGraph.addNode(new GraphNode("T4_2", 584, 109));
        schoolGraph.addNode(new GraphNode("T5_2", 665, 109));
        schoolGraph.addNode(new GraphNode("T6_2", 584, 424));
        schoolGraph.addNode(new GraphNode("T7_2", 460, 391));
        schoolGraph.addNode(new GraphNode("T8_2", 833, 308));
        schoolGraph.addNode(new GraphNode("T9_2", 833, 233));
        
        // Waypoints:
        
        schoolGraph.addNode(new GraphNode("P200", 489, 391));
        schoolGraph.addNode(new GraphNode("P201", 507, 391));
        schoolGraph.addNode(new GraphNode("P202", 517, 391));
        schoolGraph.addNode(new GraphNode("P203", 538, 391));
        schoolGraph.addNode(new GraphNode("P204", 569, 391));
        schoolGraph.addNode(new GraphNode("P205", 584, 391));
        schoolGraph.addNode(new GraphNode("P206", 584, 401));
        schoolGraph.addNode(new GraphNode("P207", 584, 413));
        schoolGraph.addNode(new GraphNode("P208", 584, 348));
        schoolGraph.addNode(new GraphNode("P209", 584, 311));
        schoolGraph.addNode(new GraphNode("P210", 569, 311));
        schoolGraph.addNode(new GraphNode("P211", 539, 311));
        schoolGraph.addNode(new GraphNode("P212", 508, 311));
        schoolGraph.addNode(new GraphNode("P213", 478, 311));
        schoolGraph.addNode(new GraphNode("P214", 569, 280));
        schoolGraph.addNode(new GraphNode("P215", 584, 280));
        schoolGraph.addNode(new GraphNode("P216", 584, 264));
        schoolGraph.addNode(new GraphNode("P217", 584, 227));
        schoolGraph.addNode(new GraphNode("P218", 584, 206));
        schoolGraph.addNode(new GraphNode("P219", 584, 170));
        schoolGraph.addNode(new GraphNode("P220", 584, 157));
        schoolGraph.addNode(new GraphNode("P221", 584, 137));
        schoolGraph.addNode(new GraphNode("P222", 584, 127));
        schoolGraph.addNode(new GraphNode("P223", 616, 264));
        schoolGraph.addNode(new GraphNode("P225", 652, 264));
        schoolGraph.addNode(new GraphNode("P227", 665, 264));
        schoolGraph.addNode(new GraphNode("P228", 665, 233));
        schoolGraph.addNode(new GraphNode("P229", 665, 181));
        schoolGraph.addNode(new GraphNode("P230", 665, 139));
        schoolGraph.addNode(new GraphNode("P231", 665, 127));
        schoolGraph.addNode(new GraphNode("P232", 694, 233));
        schoolGraph.addNode(new GraphNode("P233", 715, 233));
        schoolGraph.addNode(new GraphNode("P234", 715, 279));
        schoolGraph.addNode(new GraphNode("P235", 715, 308));
        schoolGraph.addNode(new GraphNode("P236", 738, 308));
        schoolGraph.addNode(new GraphNode("P237", 768, 308));
        schoolGraph.addNode(new GraphNode("P238", 697, 279));
        schoolGraph.addNode(new GraphNode("P239", 783, 308));
        schoolGraph.addNode(new GraphNode("P240", 817, 308));
        schoolGraph.addNode(new GraphNode("P241", 740, 233));
        schoolGraph.addNode(new GraphNode("P242", 758, 233));
        schoolGraph.addNode(new GraphNode("P243", 770, 233));
        schoolGraph.addNode(new GraphNode("P244", 789, 233));
        schoolGraph.addNode(new GraphNode("P246", 818, 233));
        schoolGraph.addNode(new GraphNode("P247", 477, 391));
        schoolGraph.addNode(new GraphNode("P248", 700, 311));
        
        // Rooms:
        
        schoolGraph.addNode(new GraphNode("Raum 200", 599, 313));
        schoolGraph.addNode(new GraphNode("Raum 203/204", 599, 348));
        schoolGraph.addNode(new GraphNode("Raum 205", 599, 401));
        schoolGraph.addNode(new GraphNode("Raum 206", 599, 413));
        schoolGraph.addNode(new GraphNode("Raum 208", 569, 413));
        schoolGraph.addNode(new GraphNode("Raum 209", 538, 413));
        schoolGraph.addNode(new GraphNode("Raum 210", 517, 413));
        schoolGraph.addNode(new GraphNode("Raum 212", 489, 413));
        schoolGraph.addNode(new GraphNode("Raum 213", 477, 413));
        schoolGraph.addNode(new GraphNode("Raum 215", 477, 374));
        schoolGraph.addNode(new GraphNode("Raum 216", 507, 374));
        schoolGraph.addNode(new GraphNode("Raum 217", 508, 329));
        schoolGraph.addNode(new GraphNode("Raum 218", 478, 329));
        schoolGraph.addNode(new GraphNode("Raum 219", 463, 311));
        schoolGraph.addNode(new GraphNode("Raum 220", 478, 293));
        schoolGraph.addNode(new GraphNode("Raum 222", 508, 293));
        schoolGraph.addNode(new GraphNode("Raum 223", 539, 293));
        schoolGraph.addNode(new GraphNode("Raum 227", 567, 227));
        schoolGraph.addNode(new GraphNode("Raum 228", 567, 206));
        schoolGraph.addNode(new GraphNode("Raum 229", 567, 170));
        schoolGraph.addNode(new GraphNode("Raum 230", 567, 157));
        schoolGraph.addNode(new GraphNode("Raum 231", 567, 127));
        schoolGraph.addNode(new GraphNode("Raum 235", 604, 127));
        schoolGraph.addNode(new GraphNode("Raum 236", 604, 139));
        schoolGraph.addNode(new GraphNode("Raum 237", 618, 246));
        schoolGraph.addNode(new GraphNode("Raum 238", 649, 246));
        schoolGraph.addNode(new GraphNode("Raum 240", 615, 282));
        schoolGraph.addNode(new GraphNode("Raum 241", 654, 282));
        schoolGraph.addNode(new GraphNode("Raum 242", 665, 282));
        schoolGraph.addNode(new GraphNode("Raum 250", 647, 139));
        schoolGraph.addNode(new GraphNode("Raum 251", 647, 127));
        schoolGraph.addNode(new GraphNode("Raum 253", 683, 127));
        schoolGraph.addNode(new GraphNode("Raum 254", 683, 138));
        schoolGraph.addNode(new GraphNode("Raum 255", 683, 181));
        schoolGraph.addNode(new GraphNode("Raum 262", 740, 216));
        schoolGraph.addNode(new GraphNode("Raum 263", 758, 216));
        schoolGraph.addNode(new GraphNode("Raum 264", 770, 216));
        schoolGraph.addNode(new GraphNode("Raum 266", 792, 216));
        schoolGraph.addNode(new GraphNode("Raum 267", 820, 216));
        schoolGraph.addNode(new GraphNode("Raum 269", 816, 250));
        schoolGraph.addNode(new GraphNode("Raum 270", 787, 250));
        schoolGraph.addNode(new GraphNode("Raum 283", 786, 291));
        schoolGraph.addNode(new GraphNode("Raum 284", 817, 291));
        schoolGraph.addNode(new GraphNode("Raum 286", 817, 335));
        schoolGraph.addNode(new GraphNode("Raum 288", 780, 335));
        schoolGraph.addNode(new GraphNode("Raum 289", 768, 335));
        schoolGraph.addNode(new GraphNode("Raum 290", 738, 335));
        schoolGraph.addNode(new GraphNode("Raum 293", 700, 335));
        
            // Third floor:
        
        // Stairs:
        
        schoolGraph.addNode(new GraphNode("T1_3", 137, 282));
        schoolGraph.addNode(new GraphNode("T2_3", 289, 308));
        schoolGraph.addNode(new GraphNode("T3_3", 289, 211));
        
        // Waypoints:
        
        schoolGraph.addNode(new GraphNode("P300", 166, 282));
        schoolGraph.addNode(new GraphNode("P301", 166, 288));
        schoolGraph.addNode(new GraphNode("P302", 166, 271));
        schoolGraph.addNode(new GraphNode("P303", 179, 271));
        schoolGraph.addNode(new GraphNode("P304", 198, 271));
        schoolGraph.addNode(new GraphNode("P305", 205, 271));
        schoolGraph.addNode(new GraphNode("P306", 218, 271));
        schoolGraph.addNode(new GraphNode("P307", 225, 271));
        schoolGraph.addNode(new GraphNode("P308", 238, 271));
        schoolGraph.addNode(new GraphNode("P309", 245, 271));
        schoolGraph.addNode(new GraphNode("P310", 251, 271));
        schoolGraph.addNode(new GraphNode("P311", 266, 271));
        schoolGraph.addNode(new GraphNode("P312", 289, 271));
        schoolGraph.addNode(new GraphNode("P313", 289, 278));
        schoolGraph.addNode(new GraphNode("P314", 289, 262));
        
        // Rooms:
        
        schoolGraph.addNode(new GraphNode("Raum 302", 166, 301));
        schoolGraph.addNode(new GraphNode("Raum 303", 186, 288));
        schoolGraph.addNode(new GraphNode("Raum 304", 205, 288));
        schoolGraph.addNode(new GraphNode("Raum 305", 225, 288));
        schoolGraph.addNode(new GraphNode("Raum 306", 245, 288));
        schoolGraph.addNode(new GraphNode("Raum 307", 266, 288));
        schoolGraph.addNode(new GraphNode("Raum 308", 314, 278));
        schoolGraph.addNode(new GraphNode("Raum 309", 310, 262));
        schoolGraph.addNode(new GraphNode("Raum 310", 251, 252));
        schoolGraph.addNode(new GraphNode("Raum 311", 238, 252));
        schoolGraph.addNode(new GraphNode("Raum 312", 218, 252));
        schoolGraph.addNode(new GraphNode("Raum 313", 198, 252));
        schoolGraph.addNode(new GraphNode("Raum 314", 179, 252));
        
        
                // Edges:
            
            // Stairs to stairs:
        
        // Ground floor to first floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_0"), schoolGraph.getNode("T1_1"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T2_0"), schoolGraph.getNode("T2_1"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T3_0"), schoolGraph.getNode("T3_1"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T4_0"), schoolGraph.getNode("T4_1"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T5_0"), schoolGraph.getNode("T5_1"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T6_0"), schoolGraph.getNode("T6_1"), 17);
        
        // First floor to second floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_1"), schoolGraph.getNode("T1_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T2_1"), schoolGraph.getNode("T2_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T3_1"), schoolGraph.getNode("T3_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T4_1"), schoolGraph.getNode("T4_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T5_1"), schoolGraph.getNode("T5_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T6_1"), schoolGraph.getNode("T6_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T7_1"), schoolGraph.getNode("T7_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T8_1"), schoolGraph.getNode("T8_2"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T9_1"), schoolGraph.getNode("T9_2"), 17);
        
        // Second floor to third floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_2"), schoolGraph.getNode("T1_3"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T2_2"), schoolGraph.getNode("T2_3"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("T3_2"), schoolGraph.getNode("T3_3"), 17);
        
            // Stairs to waypoints:
        
        // Ground floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_0"), schoolGraph.getNode("P005"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T2_0"), schoolGraph.getNode("P034"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T3_0"), schoolGraph.getNode("P026"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("T4_0"), schoolGraph.getNode("P014"), 2);
        schoolGraph.addEdge(schoolGraph.getNode("T5_0"), schoolGraph.getNode("P025"), 2);
        schoolGraph.addEdge(schoolGraph.getNode("T6_0"), schoolGraph.getNode("P000"), 34.5);
        
        // First floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_1"), schoolGraph.getNode("P111"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T2_1"), schoolGraph.getNode("P136"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T3_1"), schoolGraph.getNode("P127"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("T4_1"), schoolGraph.getNode("P119"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T5_1"), schoolGraph.getNode("P126"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T6_1"), schoolGraph.getNode("P106"), 6);
        schoolGraph.addEdge(schoolGraph.getNode("T7_1"), schoolGraph.getNode("P100"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T8_1"), schoolGraph.getNode("P142"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T9_1"), schoolGraph.getNode("P135"), 1);
        
        // Second floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_2"), schoolGraph.getNode("P214"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T2_2"), schoolGraph.getNode("P238"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T3_2"), schoolGraph.getNode("P232"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T4_2"), schoolGraph.getNode("P222"), 0.5);
        schoolGraph.addEdge(schoolGraph.getNode("T5_2"), schoolGraph.getNode("P231"), 0.5);
        schoolGraph.addEdge(schoolGraph.getNode("T6_2"), schoolGraph.getNode("P207"), 1.5);
        schoolGraph.addEdge(schoolGraph.getNode("T7_2"), schoolGraph.getNode("P247"), 2.5);
        schoolGraph.addEdge(schoolGraph.getNode("T8_2"), schoolGraph.getNode("P240"), 1.5);
        schoolGraph.addEdge(schoolGraph.getNode("T9_2"), schoolGraph.getNode("P246"), 1.5);
        
        // Third floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("T1_3"), schoolGraph.getNode("P300"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("T2_3"), schoolGraph.getNode("P313"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("T3_3"), schoolGraph.getNode("P314"), 6.5);
        
            // Waypoints to waypoints:
        
        // Ground floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P000"), schoolGraph.getNode("P001"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P000"), schoolGraph.getNode("P004"), 7.5);
        schoolGraph.addEdge(schoolGraph.getNode("P001"), schoolGraph.getNode("P002"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("P001"), schoolGraph.getNode("P005"), 7.5);
        schoolGraph.addEdge(schoolGraph.getNode("P002"), schoolGraph.getNode("P003"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P004"), schoolGraph.getNode("P005"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P004"), schoolGraph.getNode("P008"), 10);
        schoolGraph.addEdge(schoolGraph.getNode("P008"), schoolGraph.getNode("P010"), 17);
        schoolGraph.addEdge(schoolGraph.getNode("P010"), schoolGraph.getNode("P011"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P011"), schoolGraph.getNode("P012"), 15);
        schoolGraph.addEdge(schoolGraph.getNode("P011"), schoolGraph.getNode("P013"), 11);
        schoolGraph.addEdge(schoolGraph.getNode("P013"), schoolGraph.getNode("P014"), 12);
        schoolGraph.addEdge(schoolGraph.getNode("P014"), schoolGraph.getNode("P016"), 10.5);
        schoolGraph.addEdge(schoolGraph.getNode("P016"), schoolGraph.getNode("P017"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P017"), schoolGraph.getNode("P018"), 2.5);
        schoolGraph.addEdge(schoolGraph.getNode("P018"), schoolGraph.getNode("P019"), 23);
        schoolGraph.addEdge(schoolGraph.getNode("P019"), schoolGraph.getNode("P020"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P020"), schoolGraph.getNode("P021"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P021"), schoolGraph.getNode("P022"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P022"), schoolGraph.getNode("P023"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("P023"), schoolGraph.getNode("P024"), 22);
        schoolGraph.addEdge(schoolGraph.getNode("P024"), schoolGraph.getNode("P025"), 13);
        schoolGraph.addEdge(schoolGraph.getNode("P026"), schoolGraph.getNode("P027"), 13);
        schoolGraph.addEdge(schoolGraph.getNode("P027"), schoolGraph.getNode("P028"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P027"), schoolGraph.getNode("P035"), 11.5);
        schoolGraph.addEdge(schoolGraph.getNode("P028"), schoolGraph.getNode("P029"), 12);
        schoolGraph.addEdge(schoolGraph.getNode("P029"), schoolGraph.getNode("P030"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P030"), schoolGraph.getNode("P032"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P032"), schoolGraph.getNode("P033"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P034"), schoolGraph.getNode("P035"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P035"), schoolGraph.getNode("P036"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P036"), schoolGraph.getNode("P037"), 12);
        schoolGraph.addEdge(schoolGraph.getNode("P037"), schoolGraph.getNode("P039"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P039"), schoolGraph.getNode("P040"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P040"), schoolGraph.getNode("P041"), 6);
        schoolGraph.addEdge(schoolGraph.getNode("P040"), schoolGraph.getNode("P042"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P042"), schoolGraph.getNode("P043"), 13);
        schoolGraph.addEdge(schoolGraph.getNode("P043"), schoolGraph.getNode("P044"), 10);
        
        //Dirty Connetion added here
        schoolGraph.addEdge(schoolGraph.getNode("P027"), schoolGraph.getNode("P023"), 17);
        
        // First floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P100"), schoolGraph.getNode("P101"), 2.5);
        schoolGraph.addEdge(schoolGraph.getNode("P101"), schoolGraph.getNode("P102"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P102"), schoolGraph.getNode("P103"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P103"), schoolGraph.getNode("P104"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P104"), schoolGraph.getNode("P105"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P105"), schoolGraph.getNode("P106"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P105"), schoolGraph.getNode("P107"), 21);
        schoolGraph.addEdge(schoolGraph.getNode("P107"), schoolGraph.getNode("P108"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P107"), schoolGraph.getNode("P112"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P108"), schoolGraph.getNode("P109"), 16);
        schoolGraph.addEdge(schoolGraph.getNode("P108"), schoolGraph.getNode("P111"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P109"), schoolGraph.getNode("P110"), 6);
        schoolGraph.addEdge(schoolGraph.getNode("P111"), schoolGraph.getNode("P112"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P112"), schoolGraph.getNode("P113"), 4.5);
        schoolGraph.addEdge(schoolGraph.getNode("P113"), schoolGraph.getNode("P114"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P113"), schoolGraph.getNode("P120"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P114"), schoolGraph.getNode("P115"), 10);
        schoolGraph.addEdge(schoolGraph.getNode("P115"), schoolGraph.getNode("P116"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P116"), schoolGraph.getNode("P117"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P117"), schoolGraph.getNode("P118"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P118"), schoolGraph.getNode("P119"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P120"), schoolGraph.getNode("P121"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P121"), schoolGraph.getNode("P122"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P122"), schoolGraph.getNode("P123"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P123"), schoolGraph.getNode("P124"), 11.5);
        schoolGraph.addEdge(schoolGraph.getNode("P123"), schoolGraph.getNode("P127"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P124"), schoolGraph.getNode("P125"), 11);
        schoolGraph.addEdge(schoolGraph.getNode("P125"), schoolGraph.getNode("P126"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P127"), schoolGraph.getNode("P128"), 13);
        schoolGraph.addEdge(schoolGraph.getNode("P128"), schoolGraph.getNode("P130"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P128"), schoolGraph.getNode("P137"), 11.5);
        schoolGraph.addEdge(schoolGraph.getNode("P130"), schoolGraph.getNode("P131"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P131"), schoolGraph.getNode("P132"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P132"), schoolGraph.getNode("P133"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P133"), schoolGraph.getNode("P134"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P134"), schoolGraph.getNode("P135"), 2.5);
        schoolGraph.addEdge(schoolGraph.getNode("P136"), schoolGraph.getNode("P137"), 7.5);
        schoolGraph.addEdge(schoolGraph.getNode("P137"), schoolGraph.getNode("P138"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P138"), schoolGraph.getNode("P139"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P139"), schoolGraph.getNode("P140"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P139"), schoolGraph.getNode("P141"), 15);
        schoolGraph.addEdge(schoolGraph.getNode("P141"), schoolGraph.getNode("P142"), 5);
        
        // Second floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P200"), schoolGraph.getNode("P201"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P200"), schoolGraph.getNode("P247"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P201"), schoolGraph.getNode("P202"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P202"), schoolGraph.getNode("P203"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P203"), schoolGraph.getNode("P204"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P204"), schoolGraph.getNode("P205"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P205"), schoolGraph.getNode("P206"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P205"), schoolGraph.getNode("P208"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P206"), schoolGraph.getNode("P207"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P208"), schoolGraph.getNode("P209"), 11.5);
        schoolGraph.addEdge(schoolGraph.getNode("P209"), schoolGraph.getNode("P210"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P209"), schoolGraph.getNode("P215"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P210"), schoolGraph.getNode("P211"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P210"), schoolGraph.getNode("P214"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P211"), schoolGraph.getNode("P212"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P212"), schoolGraph.getNode("P213"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P214"), schoolGraph.getNode("P215"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P215"), schoolGraph.getNode("P216"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P216"), schoolGraph.getNode("P217"), 6.5);
        schoolGraph.addEdge(schoolGraph.getNode("P216"), schoolGraph.getNode("P223"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P217"), schoolGraph.getNode("P218"), 9.5);
        schoolGraph.addEdge(schoolGraph.getNode("P218"), schoolGraph.getNode("P219"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P219"), schoolGraph.getNode("P220"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P220"), schoolGraph.getNode("P221"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P221"), schoolGraph.getNode("P222"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P223"), schoolGraph.getNode("P225"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P225"), schoolGraph.getNode("P227"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P227"), schoolGraph.getNode("P228"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P228"), schoolGraph.getNode("P229"), 12);
        schoolGraph.addEdge(schoolGraph.getNode("P228"), schoolGraph.getNode("P232"), 7.5);
        schoolGraph.addEdge(schoolGraph.getNode("P229"), schoolGraph.getNode("P230"), 10.5);
        schoolGraph.addEdge(schoolGraph.getNode("P230"), schoolGraph.getNode("P231"), 6.5);
        schoolGraph.addEdge(schoolGraph.getNode("P232"), schoolGraph.getNode("P233"), 12);
        schoolGraph.addEdge(schoolGraph.getNode("P233"), schoolGraph.getNode("P234"), 11);
        schoolGraph.addEdge(schoolGraph.getNode("P233"), schoolGraph.getNode("P241"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P234"), schoolGraph.getNode("P235"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P234"), schoolGraph.getNode("P238"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P235"), schoolGraph.getNode("P236"), 8);
        schoolGraph.addEdge(schoolGraph.getNode("P235"), schoolGraph.getNode("P248"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P236"), schoolGraph.getNode("P237"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P237"), schoolGraph.getNode("P239"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P239"), schoolGraph.getNode("P240"), 9);
        schoolGraph.addEdge(schoolGraph.getNode("P241"), schoolGraph.getNode("P242"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P242"), schoolGraph.getNode("P243"), 8.5);
        schoolGraph.addEdge(schoolGraph.getNode("P243"), schoolGraph.getNode("P244"), 3);
        schoolGraph.addEdge(schoolGraph.getNode("P244"), schoolGraph.getNode("P246"), 8.5);
        
        // Third floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P300"), schoolGraph.getNode("P301"), 0.5);
        schoolGraph.addEdge(schoolGraph.getNode("P300"), schoolGraph.getNode("P302"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P302"), schoolGraph.getNode("P303"), 3.5);
        schoolGraph.addEdge(schoolGraph.getNode("P303"), schoolGraph.getNode("P304"), 5);
        schoolGraph.addEdge(schoolGraph.getNode("P304"), schoolGraph.getNode("P305"), 0.5);
        schoolGraph.addEdge(schoolGraph.getNode("P305"), schoolGraph.getNode("P306"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P306"), schoolGraph.getNode("P307"), 2);
        schoolGraph.addEdge(schoolGraph.getNode("P307"), schoolGraph.getNode("P308"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P308"), schoolGraph.getNode("P309"), 2);
        schoolGraph.addEdge(schoolGraph.getNode("P309"), schoolGraph.getNode("P310"), 2);
        schoolGraph.addEdge(schoolGraph.getNode("P310"), schoolGraph.getNode("P311"), 1.5);
        schoolGraph.addEdge(schoolGraph.getNode("P311"), schoolGraph.getNode("P312"), 4);
        schoolGraph.addEdge(schoolGraph.getNode("P312"), schoolGraph.getNode("P313"), 1);
        schoolGraph.addEdge(schoolGraph.getNode("P312"), schoolGraph.getNode("P314"), 3);
        
            // Waypoints to rooms:
        
        // Ground floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P007"), schoolGraph.getNode("Bibliothek"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P004"), schoolGraph.getNode("Foyer"), 13);
        schoolGraph.addEdge(schoolGraph.getNode("P007"), schoolGraph.getNode("Foyer"), 7);
        schoolGraph.addEdge(schoolGraph.getNode("P008"), schoolGraph.getNode("Foyer"), 15);
        schoolGraph.addEdge(schoolGraph.getNode("P026"), schoolGraph.getNode("Foyer"), 19);
        schoolGraph.addEdge(schoolGraph.getNode("P002"), schoolGraph.getNode("WC Herren"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P003"), schoolGraph.getNode("WC Damen"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P003"), schoolGraph.getNode("Mensa"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("T4_0"), schoolGraph.getNode("Saftladen"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P010"), schoolGraph.getNode("Raum 38"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P011"), schoolGraph.getNode("Raum 39"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P012"), schoolGraph.getNode("Raum 42"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P017"), schoolGraph.getNode("Werkraum 8"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P018"), schoolGraph.getNode("Werkraum 14"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P019"), schoolGraph.getNode("Werkraum 15"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P020"), schoolGraph.getNode("Werkraum 17"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P021"), schoolGraph.getNode("Werkraum 20"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P022"), schoolGraph.getNode("Werkraum 21"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P023"), schoolGraph.getNode("Werkraum 24"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P022"), schoolGraph.getNode("Werkraum 27"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P016"), schoolGraph.getNode("Werkraum 32"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("T4_0"), schoolGraph.getNode("Kunstraum 53"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P028"), schoolGraph.getNode("Raum 63"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P029"), schoolGraph.getNode("Raum 64"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P030"), schoolGraph.getNode("Raum 65"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P032"), schoolGraph.getNode("Raum 66"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P033"), schoolGraph.getNode("Raum 67"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P033"), schoolGraph.getNode("Raum 70"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P032"), schoolGraph.getNode("Raum 71"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P030"), schoolGraph.getNode("Raum 72"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P029"), schoolGraph.getNode("Raum 73"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P039"), schoolGraph.getNode("Raum 87"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P042"), schoolGraph.getNode("Raum 88"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P043"), schoolGraph.getNode("Raum 89"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P043"), schoolGraph.getNode("Raum 90"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P044"), schoolGraph.getNode("Raum 92"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P044"), schoolGraph.getNode("Raum 93"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P041"), schoolGraph.getNode("Raum 94"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P041"), schoolGraph.getNode("Raum 95"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P041"), schoolGraph.getNode("Raum 96"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P037"), schoolGraph.getNode("Raum 97"), 0.1);
        
        // First floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P110"), schoolGraph.getNode("Lehrerzimmer"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P110"), schoolGraph.getNode("Büro der Schulleitung/Sekretariat"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P109"), schoolGraph.getNode("Büro der stellv. Schulleitung"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P106"), schoolGraph.getNode("Raum 104"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P104"), schoolGraph.getNode("Raum 106"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P103"), schoolGraph.getNode("Raum 107"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P102"), schoolGraph.getNode("Raum 108"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P101"), schoolGraph.getNode("Raum 109"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P100"), schoolGraph.getNode("Raum 110"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P114"), schoolGraph.getNode("Raum 132"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P115"), schoolGraph.getNode("Raum 134"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P116"), schoolGraph.getNode("Raum 135"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P117"), schoolGraph.getNode("Raum 136"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P119"), schoolGraph.getNode("Raum 137"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P119"), schoolGraph.getNode("Raum 141"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P118"), schoolGraph.getNode("Raum 142"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P120"), schoolGraph.getNode("Raum 144"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P121"), schoolGraph.getNode("Raum 145"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P125"), schoolGraph.getNode("Raum 150"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P126"), schoolGraph.getNode("Raum 151"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P126"), schoolGraph.getNode("Raum 154"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P125"), schoolGraph.getNode("Raum 155"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P124"), schoolGraph.getNode("Raum 156"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P130"), schoolGraph.getNode("Raum 166"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P131"), schoolGraph.getNode("Raum 167"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P132"), schoolGraph.getNode("Raum 168"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P133"), schoolGraph.getNode("Raum 169"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P134"), schoolGraph.getNode("Raum 170"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P135"), schoolGraph.getNode("Raum 171"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P135"), schoolGraph.getNode("Raum 174"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P133"), schoolGraph.getNode("Raum 175"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P141"), schoolGraph.getNode("Raum 184"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P142"), schoolGraph.getNode("Raum 185"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P142"), schoolGraph.getNode("Raum 188"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P141"), schoolGraph.getNode("Raum 189"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P140"), schoolGraph.getNode("Raum 190"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P138"), schoolGraph.getNode("Raum 191"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P138"), schoolGraph.getNode("Raum 192/193"), 0.1);
        
        // Second floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P209"), schoolGraph.getNode("Raum 200"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P208"), schoolGraph.getNode("Raum 203/204"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P206"), schoolGraph.getNode("Raum 205"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P207"), schoolGraph.getNode("Raum 206"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P204"), schoolGraph.getNode("Raum 208"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P203"), schoolGraph.getNode("Raum 209"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P202"), schoolGraph.getNode("Raum 210"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P200"), schoolGraph.getNode("Raum 212"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P247"), schoolGraph.getNode("Raum 213"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P247"), schoolGraph.getNode("Raum 215"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P201"), schoolGraph.getNode("Raum 216"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P212"), schoolGraph.getNode("Raum 217"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P213"), schoolGraph.getNode("Raum 218"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P213"), schoolGraph.getNode("Raum 219"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P213"), schoolGraph.getNode("Raum 220"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P212"), schoolGraph.getNode("Raum 222"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P211"), schoolGraph.getNode("Raum 223"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P217"), schoolGraph.getNode("Raum 227"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P218"), schoolGraph.getNode("Raum 228"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P219"), schoolGraph.getNode("Raum 229"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P220"), schoolGraph.getNode("Raum 230"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P222"), schoolGraph.getNode("Raum 231"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P222"), schoolGraph.getNode("Raum 235"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P221"), schoolGraph.getNode("Raum 236"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P223"), schoolGraph.getNode("Raum 237"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P225"), schoolGraph.getNode("Raum 238"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P223"), schoolGraph.getNode("Raum 240"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P225"), schoolGraph.getNode("Raum 241"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P227"), schoolGraph.getNode("Raum 242"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P230"), schoolGraph.getNode("Raum 250"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P231"), schoolGraph.getNode("Raum 251"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P231"), schoolGraph.getNode("Raum 253"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P230"), schoolGraph.getNode("Raum 254"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P229"), schoolGraph.getNode("Raum 255"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P241"), schoolGraph.getNode("Raum 262"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P242"), schoolGraph.getNode("Raum 263"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P243"), schoolGraph.getNode("Raum 264"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P244"), schoolGraph.getNode("Raum 266"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P246"), schoolGraph.getNode("Raum 267"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P246"), schoolGraph.getNode("Raum 269"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P244"), schoolGraph.getNode("Raum 270"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P239"), schoolGraph.getNode("Raum 283"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P240"), schoolGraph.getNode("Raum 284"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P240"), schoolGraph.getNode("Raum 286"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P239"), schoolGraph.getNode("Raum 288"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P237"), schoolGraph.getNode("Raum 289"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P236"), schoolGraph.getNode("Raum 290"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P248"), schoolGraph.getNode("Raum 293"), 0.1);
        
        // Third floor:
        
        schoolGraph.addEdge(schoolGraph.getNode("P301"), schoolGraph.getNode("Raum 302"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P301"), schoolGraph.getNode("Raum 303"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P305"), schoolGraph.getNode("Raum 304"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P307"), schoolGraph.getNode("Raum 305"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P309"), schoolGraph.getNode("Raum 306"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P311"), schoolGraph.getNode("Raum 307"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P313"), schoolGraph.getNode("Raum 308"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P314"), schoolGraph.getNode("Raum 309"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P310"), schoolGraph.getNode("Raum 310"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P308"), schoolGraph.getNode("Raum 311"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P306"), schoolGraph.getNode("Raum 312"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P304"), schoolGraph.getNode("Raum 313"), 0.1);
        schoolGraph.addEdge(schoolGraph.getNode("P303"), schoolGraph.getNode("Raum 314"), 0.1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
